name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  get: 4.6.5
  flutter:
    sdk: flutter
  get_hooks: any
  flutter_hooks: ^0.18.5+1
  # Install flutter hooks

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  get_hooks:
    path: ../

flutter:
  uses-material-design: true

get_cli:
  sub_folder: false
