name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  get_help: any
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_lorem: ^2.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides: 
  get_help: 
    path: ../

flutter: 
  uses-material-design: true

get_cli: 
  sub_folder: false

