import 'package:flutter/material.dart';

import 'package:get/get.dart';
import 'package:get_help/get_help.dart';

import 'app/routes/app_pages.dart';

/// The folder structure for this app was generated by the amazing
/// [get_cli](https://pub.dev/packages/get_cli) package. Please do note the 
/// get_cli fields at the bottom of the pubspec.yaml file:
/// 
/// ```yaml
/// get_cli:
///   sub_folder: false
/// ```
///
/// This is defined to tell the generator to create pages without subfolders 
/// which is more in line with how Getx_pattern was designed.
void main() {
  runApp(
    GetMaterialApp(
      title: "Application",
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
    ),
  );
}

class HomeBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<HomeController>(
      () => HomeController(),
    );
  }
}

class HomeController extends GetxController {}

class HomeView extends GetBuilderView<HomeController> {
  const HomeView({super.key});

  @override
  Widget builder(context, controller) {
    return Scaffold(
      appBar: AppBar(title: const Text('HomeView')),
      body: Container(),
    );
  }
}
